---

- copy: >
    src=nginx.limits.conf
    dest=/etc/security/limits.d
    mode=400 owner=root group=root

- name: packages
  yum: name="{{ item }}" state=present
  with_items:
    - nginx

- file: state=directory dest=/etc/nginx/vhosts.d owner=root mode=444
- copy: >
    src={{item}}
    dest=/etc/nginx/conf.d/
    owner=root mode=444
  notify: reload nginx
  with_items:
    - vhosts.conf
    - performance.conf

- file: state=directory dest=/var/cache/nginx owner=nginx mode=700

- name: service
  service: name=nginx enabled=true

- firewalld: >
    service=http
    state=enabled
    permanent=true
    immediate=true

- meta: flush_handlers
