---

- name: set limits for nginx
  copy: >
    src=nginx.limits.conf
    dest=/etc/security/limits.d
    mode=0400 owner=root group=root

- name: install nginx
  yum: name="{{ item }}" state=present
  with_items:
    - nginx

- name: create nginx/vhosts.d
  # mode=0751 -- users are able to read their nginx vhost file but can not see which other domains are present
  file: state=directory dest=/etc/nginx/vhosts.d owner=root mode=0751

- name: add custom settings for vhosts/performance
  copy: >
    src={{item}}
    dest=/etc/nginx/conf.d/
    owner=root mode=0444
  notify: reload nginx
  with_items:
    - vhosts.conf
    - performance.conf

- name: enable nginx
  service: name=nginx enabled=true

- name: allow HTTP(S) in the firewall
  firewalld: port={{ item }}/tcp immediate=true permanent=true state=enabled
  with_items:
    - 80
    - 443

- meta: flush_handlers

