---

- name: set limits for nginx
  copy: >
    src=nginx.limits.conf
    dest=/etc/security/limits.d
    mode=0400 owner=root group=root

- name: install nginx and logrotate
  yum:
    name:
      - nginx
      - logrotate
    state: present

- name: allow nginx to initiate network connections (HTTP reverse proxy, OCSP stapling)
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux != False

- name: create nginx/vhosts.d
  # mode=0751 -- users are able to read their nginx vhost file but can not see which other domains are present
  file: state=directory dest=/etc/nginx/vhosts.d owner=root mode=0751

- name: add custom settings for vhosts/performance
  copy: >
    src={{item}}
    dest=/etc/nginx/conf.d/
    owner=root mode=0444
  notify: restart nginx
  with_items:
    - vhosts.conf
    - performance.conf

- name: enable nginx
  # "notify: restart nginx" will take care of starting nginx
  # (and handle config changes with ansible, not just the initial install)
  service: name=nginx enabled=true

- name: allow HTTP(S) in the firewall
  firewalld: port={{ item }}/tcp immediate=true permanent=true state=enabled
  with_items:
    - 80
    - 443

- name: enable logrotation for nginx vhosts
  copy: >
    src=logrotate-nginx-vhosts.conf
    dest=/etc/logrotate.d/nginx-vhosts.conf
    owner=root group=root
    mode=0644

# ,--- renew support for nginx -------------------------------------------------
- name: check if letsencrypt/renew.d is present
  stat: path=/etc/letsencrypt/renew.d/
  register: letsencrypt_renewd

- name: install nginx hook when certificates are installed
  copy:
    src=letsencrypt-renew.sh
    dest=/etc/letsencrypt/renew.d/nginx.sh
    owner=root group=root
    mode=0755
  when: letsencrypt_renewd.stat.exists
# `--- renew support for nginx -------------------------------------------------

- name: configure "map_hash_bucket_size"
  copy:
    src=_bucket_size.conf
    dest=/etc/nginx/conf.d/_bucket_size.conf
    owner=root group=root
    mode=0644
  notify: restart nginx

- name: define anonymized log format
  copy:
    src=anonymized_logging.conf
    dest=/etc/nginx/conf.d/anonymized_logging.conf
    owner=root group=root
    mode=0644
  notify: restart nginx

- name: create nginx/global.include.d
  file: state=directory dest=/etc/nginx/global.include.d owner=root mode=0755

- name: configure global acme challenge location
  copy:
    src=global-acme-challenge.conf
    dest=/etc/nginx/global.include.d/global-acme-challenge.conf
    owner=root group=root
    mode=0644
  notify: restart nginx

- name: use global includes also for the default server
  copy:
    src=default-server-global-includes.conf
    dest=/etc/nginx/default.d/global-includes.conf
    owner=root group=root
    mode=0644
  notify: restart nginx

- meta: flush_handlers

