---

- name: set limits for nginx
  copy: >
    src=nginx.limits.conf
    dest=/etc/security/limits.d
    mode=0400 owner=root group=root

- name: install nginx and logrotate
  yum: name="{{ item }}" state=present
  with_items:
    - nginx
    - logrotate

- name: create nginx/vhosts.d
  # mode=0751 -- users are able to read their nginx vhost file but can not see which other domains are present
  file: state=directory dest=/etc/nginx/vhosts.d owner=root mode=0751

- name: add custom settings for vhosts/performance
  copy: >
    src={{item}}
    dest=/etc/nginx/conf.d/
    owner=root mode=0444
  notify: restart nginx
  with_items:
    - vhosts.conf
    - performance.conf

- name: enable nginx
  # "notify: restart nginx" will take care of starting nginx
  # (and handle config changes with ansible, not just the initial install)
  service: name=nginx enabled=true

- name: allow HTTP(S) in the firewall
  firewalld: port={{ item }}/tcp immediate=true permanent=true state=enabled
  with_items:
    - 80
    - 443

- name: enable logrotation for nginx vhosts
  copy: >
    src=logrotate-nginx-vhosts.conf
    dest=/etc/logrotate.d/nginx-vhosts.conf
    owner=root group=root
    mode=0644

# ,--- renew support for nginx -------------------------------------------------
- name: check if letsencrypt/renew.d is present
  stat: path=/etc/letsencrypt/renew.d/
  register: letsencrypt_renewd

- name: install nginx hook when certificates are installed
  copy:
    src=letsencrypt-renew.sh
    dest=/etc/letsencrypt/renew.d/nginx.sh
    owner=root group=root
    mode=0755
  when: letsencrypt_renewd.stat.exists
# `--- renew support for nginx -------------------------------------------------

- meta: flush_handlers

