# This file is not included in the "regular" nginx role by default but can
# be included by other roles
# (I did not want to presume a specific file system layout.)
#
# variables:
#   item
#     - user
#     - domain
# (assumes nginx has user nginx/group nginx)

- set_fact: vhost_username={{ item.user }}
- set_fact: vhost_domain={{ item.domain }}

- name: setup vhost filesystem for {{ vhost_username }}/{{ vhost_domain }}
  include: roles/nginx/tasks/nginx-vhost-filesystem.yml


- name: add nginx vhost
  copy:
    src: host_files/{{ inventory_hostname }}/nginx/{{ vhost_username }}-{{ vhost_domain }}.conf
    dest: /etc/nginx/vhosts.d/{{ vhost_username }}-{{ vhost_domain }}.conf
    owner: nginx
    group: "{{ vhost_usergroup }}"
    mode: 0640
  notify: restart nginx

- meta: flush_handlers

