---

- name: kvm and libvirt packages
  yum: name={{ item }} state=present
  with_items:
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-driver-qemu
    - libvirt-daemon-driver-network
    - libvirt-daemon-kvm
    - libvirt-daemon-config-network
    - libvirt-daemon-driver-interface

- name: disable rpcbind service
  service: name=rpcbind state=stopped enabled=no

- name: configure networkd
  copy: src=host_files/{{ inventory_hostname }}/10-eth0.network dest="/etc/systemd/network/10-{{ eth_device }}.network"

- name: create libvirt hooks directors
  file: path=/etc/libvirt/hooks/ state=directory owner=root group=root mode=0700

- name: check for VM IP routing configuration
  local_action: stat path=host_files/{{ inventory_hostname }}/routed_ips
  register: routed_ips
  ignore_errors: True

- name: copy VM IP routing configuration
  copy: src=host_files/{{ inventory_hostname }}/routed_ips dest="/etc/sysconfig/" mode=0644
  when: routed_ips.stat.exists

- name: copy libvirt network hook script
  copy: src=libvirt-hooks-network.py dest="/etc/libvirt/hooks/network" mode=0755

- name: enable libvirtd service
  service: name=libvirtd state=started enabled=yes

- name: enable libvirt-guests service
  service: name=libvirt-guests state=started enabled=yes

# by default libvirt-guests should "suspend" guests but that did not work out
# for me (February 2017, CentOS 7) so let's just shut them down.
- name: poweroff guests on shutdown
  lineinfile:
    dest: /etc/sysconfig/libvirt-guests
    line: "ON_SHUTDOWN=shutdown"
    regexp: "^ON_SHUTDOWN="

