---

- hosts: all:!localhost
  remote_user: root
  roles:
  - role: common
    tags: common


- hosts: staging
  remote_user: root
  roles:
  - role: vm-guest
    tags: vm-guest
  - role: exim-relay
    tags: exim-relay

