---

- name: install dovecot
  yum:
    name:
      - dovecot
      - dovecot-pigeonhole # sieve functionality
    state: present

# dovecot files need to be readable for group "mail" because the dovecot-lda is
# run by exim as "mail" user.
- name: copy dovecot.conf
  copy: src=dovecot/dovecot.conf dest=/etc/dovecot/dovecot.conf owner=root group=mail mode=0640
- name: copy dovecot-sql.conf.ext
  copy: src=dovecot/dovecot-sql.conf.ext dest=/etc/dovecot/dovecot-sql.conf.ext owner=root group=mail mode=0644
- name: copy dovecot/conf.d
  copy: src={{ item }} dest=/etc/dovecot/conf.d/ owner=root group=mail mode=0640
  with_fileglob:
    - dovecot/conf.d/*.conf
  no_log: True

# create symlinks to certificates - hopefully "10-ssl.conf" is more generic that way.
- file: path=/etc/dovecot/tls state=directory owner=root group=mail mode=0750

# not all VMs should use letsencrypt
- file: src=/etc/letsencrypt/live/{{ hostname_letsencrypt }}/fullchain.pem dest=/etc/dovecot/tls/fullchain.pem state=link
  when: use_letsencrypt_cert
- file: src=/etc/letsencrypt/live/{{ hostname_letsencrypt }}/privkey.pem dest=/etc/dovecot/tls/privkey.pem state=link
  when: use_letsencrypt_cert

- file: src=/etc/pki/dovecot/certs/dovecot.pem dest=/etc/dovecot/tls/fullchain.pem state=link
  when: not use_letsencrypt_cert
- file: src=/etc/pki/dovecot/private/dovecot.pem dest=/etc/dovecot/tls/privkey.pem state=link
  when: not use_letsencrypt_cert

# ,--- renew support for dovecot -----------------------------------------------
- name: check if letsencrypt/renew.d is present
  stat: path=/etc/letsencrypt/renew.d/
  register: letsencrypt_renewd

- name: install dovecot hook when certificates are installed
  copy:
    src=letsencrypt-renew.sh
    dest=/etc/letsencrypt/renew.d/dovecot.sh
    owner=root group=root
    mode=0755
  when: letsencrypt_renewd.stat.exists
# `--- renew support for dovecot -----------------------------------------------

- name: enable dovecot
  service: name=dovecot state=started enabled=true

- firewalld: port=993/tcp immediate=true permanent=true state=enabled
- firewalld: port=995/tcp immediate=true permanent=true state=enabled

# block unencrypted pop3/imap by default
- firewalld: port=110/tcp immediate=true permanent=true state=disabled
- firewalld: port=143/tcp immediate=true permanent=true state=disabled

