---
# This role contains plays for mailserver hosts using Exim and dovecot.

- name: create /srv/mail
  file:
      path: /srv/mail
      state: directory
      owner: root
      group: mail
      # dovecot-lda runs with group "mail" and it needs to store message there
      mode:  0770

- include: userdb.yml

- include: rspamd.yml

# open up ports for exim
- name: allow SMTP ports in the firewall
  firewalld: port={{ item }}/tcp immediate=true permanent=true state=enabled
  with_items:
    - 25
    - 465
    - 587


- include: dovecot.yml

- meta: flush_handlers

