---
# This role contains plays for mailserver hosts using Exim and dovecot.

- name: create /srv/mail
  file:
      path: /srv/mail
      state: directory
      owner: root
      group: mail
      # dovecot-lda runs with group "mail" and it needs to store message there
      mode:  0770

- include: userdb.yml

# open up ports for exim
- name: allow access to port 25 (tcp)
  firewalld: port=25/tcp immediate=true permanent=true state=enabled
- name: allow access to port 465 (tcp)
  firewalld: port=465/tcp immediate=true permanent=true state=enabled
- name: allow access to port 587 (tcp)
  firewalld: port=587/tcp immediate=true permanent=true state=enabled

- include: dovecot.yml

- meta: flush_handlers

