---

- name: install rspamd
  yum:
    name: rspamd
    state: present

- name: create rspamd/local.d
  file: path=/etc/rspamd/local.d state=directory owner=rspamd group=rspamd mode=0750


# add host-specific "worker-controller.inc" if it exists
- name: check if host-specific "worker-controller.inc" exists
  local_action: stat path=host_files/{{ inventory_hostname }}/rspamd-worker-controller.inc
  register: rspamd_worker_controller_file

- name: copy custom configuration for worker-controller.inc
  copy:
    src: "host_files/{{ inventory_hostname }}/rspamd-worker-controller.inc"
    dest: /etc/rspamd/local.d/worker-controller.inc
    owner: rspamd
    group: rspamd
    mode: 0640
  when: rspamd_worker_controller_file.stat.exists


# Using "0" as threshold for BAYES_HAM autolearning seems to be a bit too
# naive as a message with a good mime structure and no negative identifiers will
# have -0.3.
- name: add custom settings for bayes autolearning
  copy: >
    src=rspamd-statistic.conf
    dest=/etc/rspamd/local.d/statistic.conf
    owner=rspamd mode=0644

# specify a higher threshold for "reject" and possibly also modify scores
# for some rules.
- name: add custom thresholds for reject
  copy: >
    src=rspamd-metrics.conf
    dest=/etc/rspamd/local.d/metrics.conf
    owner=rspamd mode=0644

- name: add custom RBL configuration
  copy: >
    src=rspamd-rbl.conf
    dest=/etc/rspamd/local.d/rbl.conf
    owner=rspamd mode=0644

- name: add custom user settings
  copy:
    src: rspamd-settings.map
    dest: /etc/rspamd/local.d/settings.map
    owner: rspamd
    group: rspamd
    mode: 0640

- name: copy rspamd.conf.local
  copy:
    src: rspamd.conf.local
    dest: /etc/rspamd/rspamd.conf.local
    owner: rspamd
    group: rspamd
    mode: 0640

- name: enable rspamd.service
  service: name=rspamd.service enabled=true state=started

