---

borg_prescript: ""
borg_postscript: ""

# I hoped that SELinux basically "just" works in CentOS but it doesn't. Even
# common services like exim, dovecot and chronyd want to use DBUS but they are
# blocked...
# I don't see huge value in having SELinux so disable it for now (and reconsider
# this decision in CentOS 8 as SELinux seems to work fine Fedora 23).
selinux_mode: disabled

# by default, updates should be applied automatically
# however some systems are too important so we want to run updates manually.
# valid values: "yes" / "no"
system_auto_updates: "yes"

sshguard: True
