---

# force hosts to enable letsencrypt explicitely. Do not try to authorize
# arbitrary domains (e.g. for testing VMs) accidentally.
# (I was unable to derive a true bool variable from the "letsencrypt_host_domains"
# variable so this information is a bit duplicated...)
use_letsencrypt_cert: False

letsencrypt_ini_path: /etc/letsencrypt/client.ini

# If "False" (default) the tasks assume that renewals should use the
# "webroot" authentication (because the webserver was set up after the first
# certificate retrieval).
# Set to "True" to use the "standalone" authenticator forever (because there is
# no webserver installed).
standalone_authenticator_only: False

# This is required because "include: fetch_certificate.yml" in main.yml
# references "letsencrypt_host_domains" and ansible tries to evaluate that
# even though the import is not executed if "use_letsencrypt" is False.
letsencrypt_host_domains: []
