---
# This role contains plays for hosts using Exim as relay (sending emails via
# dedicated mail server/"smart host")

- yum: name={{ item }} state=present
  with_items:
    - exim

- yum: name={{ item }} state=absent
  with_items:
    - postfix


# configuration files for exim must not be owned by the Exim runtime user ("exim")
# and must not be writable for that user (these are constraints enforced by
# exim itself).
# The idea is that Exim can not be tricked into modifying its own config in case
# a bug is being exploited.
# Also let's make the file unreadable for all other users just in case there
# are secrets inside (e.g. passwords).
- name: copy basic exim.conf
  copy:
    src: exim.conf
    dest: /etc/exim/exim.conf
    owner: root
    group: exim
    mode: 0640

# copy host-specific configuration files for exim
- copy:
    content: "{{ exim_local_conf }}"
    dest: /etc/exim/local.conf
    owner: root
    group: exim
    mode: 0640

- copy:
    src: host_files/{{ inventory_hostname }}/exim-rewrite.conf
    dest: /etc/exim/rewrite.conf
    owner: root
    group: exim
    mode: 0640


- name: validate exim configuration
  command: exim -C /etc/exim/exim.conf -bV

- name: enable exim
  service: name=exim state=started enabled=true

- meta: flush_handlers

