---
# This role contains plays for hosts using Exim as relay (sending emails via
# dedicated mail server/"smart host")

- name: enable copr repo for exim in epel8
  copy:
    src: fschwarz-exim-epel8.repo
    dest: /etc/yum.repos.d/
  when: is_centos8


- name: install exim
  yum:
    name: exim
    state: present

- name: uninstall postfix
  yum:
    name: postfix
    state: absent


# configuration files for exim must not be owned by the Exim runtime user ("exim")
# and must not be writable for that user (these are constraints enforced by
# exim itself).
# The idea is that Exim can not be tricked into modifying its own config in case
# a bug is being exploited.
# Also let's make the file unreadable for all other users just in case there
# are secrets inside (e.g. passwords).
- name: copy basic exim.conf
  copy: src=exim.conf dest=/etc/exim/exim.conf owner=root group=exim mode=0640
  register: exim_conf



- name: copy exim/acls.conf
  copy: src={{ exim_acls_conf_path }} dest=/etc/exim/acls.conf owner=root group=exim mode=0640
  register: exim_acls_conf

- name: create exim/acls.d
  file: path=/etc/exim/acls.d state=directory owner=root group=exim mode=0750

- name: copy acl definitions from exim/acls.d
  copy: src={{ item }} dest=/etc/exim/acls.d/ owner=root group=exim mode=0640
  with_fileglob:
    - acls.d/*.conf
  no_log: True

# copy host-specific ACLs if present
# Unfortunately we can't put the wildcard in the "with_fileglob" (if the
# host-specific directory is not present) as this would lead to ansible
# warnings (this used to work with ansible 1.x): "Unable to find ..."
# Also "with" clauses are executed before evaluating "when" so this can't be
# used neither.
# (I assume this is so users can exclude individual items using "when").
# https://github.com/ansible/ansible/issues/13296#issuecomment-159768329
# In the end we can only execute a command locally and loop over stdout.
- name: gather if we have host-specific exim acls
  # "| cat" which "swallow" a non-zero return code from "ls" (if the directory
  # is not present at all"
  local_action: shell ls -1 host_files/{{ inventory_hostname }}/exim-acls.d/*.conf 2>/dev/null | cat
  register: exim_acls_d

- name: copy host-specifc exim ACLs
  copy: src={{ item }} dest=/etc/exim/acls.d/ owner=root group=exim mode=0640
  with_items: "{{ exim_acls_d.stdout_lines }}"


- name: copy exim/role.conf
  copy: src={{ exim_role_conf_path }} dest=/etc/exim/role.conf owner=root group=exim mode=0640
  register: exim_role_conf



- name: copy exim/routers.conf
  copy: src={{ exim_routers_conf_path }}  dest=/etc/exim/routers.conf owner=root group=exim mode=0640
  register: exim_routers_conf

- name: create exim/routers.d
  file: path=/etc/exim/routers.d state=directory owner=root group=exim mode=0750

- name: copy router definitions from exim/routers.d
  copy: src={{ item }} dest=/etc/exim/routers.d/ owner=root group=exim mode=0640
  with_fileglob:
    - "{{ exim_role }}/routers.d/*.conf"
  no_log: True

# see exim_acls_d for more explanantion
- name: gather if we have host-specific exim routers
  local_action: shell ls -1 host_files/{{ inventory_hostname }}/exim-routers.d/*.conf 2>/dev/null | cat
  register: exim_routers_d

- name: copy host-specific router definitions
  copy: src={{ item }} dest=/etc/exim/routers.d/ owner=root group=exim mode=0640
  with_items: "{{ exim_routers_d.stdout_lines }}"



- name: copy exim/transports.conf
  copy: src={{ exim_transports_conf_path }}  dest=/etc/exim/transports.conf owner=root group=exim mode=0640
  register: exim_transports_conf

- name: create exim/transports.d
  file: path=/etc/exim/transports.d state=directory owner=root group=exim mode=0750

- name: copy router definitions from exim/transports.d
  copy: src={{ item }} dest=/etc/exim/transports.d/ owner=root group=exim mode=0640
  with_fileglob:
    - "{{ exim_role }}/transports.d/*.conf"
  no_log: True

# see exim_acls_d for more explanantion
- name: gather if we have host-specific exim transports
  local_action: shell ls -1 host_files/{{ inventory_hostname }}/exim-transports.d/*.conf 2>/dev/null | cat
  register: exim_transports_d

- name: copy host-specific transport definitions
  copy: src={{ item }} dest=/etc/exim/transports.d/ owner=root group=exim mode=0640
  with_items: "{{ exim_transports_d.stdout_lines }}"



- name: copy exim/rewrite.conf
  copy: src={{ exim_rewrite_conf_path }}  dest=/etc/exim/rewrite.conf owner=root group=exim mode=0640
  register: exim_rewrite_conf

- name: copy exim/authenticators.conf
  copy: src={{ exim_authenticators_conf_path }}  dest=/etc/exim/authenticators.conf owner=root group=exim mode=0640
  register: exim_authenticators_conf


# copy host-specific configuration files for exim
- name: check if host-specific exim.local exists as file
  local_action: stat path=host_files/{{ inventory_hostname }}/exim-local.conf
  register: exim_local_conf_file

- name: copy host-specific configuration file for exim
  copy:
    src: "host_files/{{ inventory_hostname }}/exim-local.conf"
    dest: /etc/exim/local.conf
    owner: root
    group: exim
    mode: 0640
  when: exim_local_conf_file.stat.exists

- name: copy host-specific configuration file for exim (from variable)
  copy:
    content: "{{ exim_local_conf }}"
    dest: /etc/exim/local.conf
    owner: root
    group: exim
    mode: 0640
  when: (exim_local_conf is defined) and (not exim_local_conf_file.stat.exists)
  register: exim_local_conf

- file: path=/etc/exim/local.conf state=absent
  when: (exim_local_conf is not defined) and (not exim_local_conf_file.stat.exists)
  register: exim_local_conf


# DKIM keys are not managed by ansible but let's create the folder at least
- name: create /etc/exim/dkim
  file:
      path: /etc/exim/dkim
      state: directory
      # be careful to set ownership/permissions correctly. Exim's "exists{}"
      # condition will just return "false" without hinting at a permission
      # problem so DKIM signing might be disabled accidentally.
      # I spent some hours debugging this until I found that the "dkim" directory
      # must use the group "exim" and not "mail". Even though the exim user
      # belongs to the "mail" group the running exim instance doesn't assume
      # these privileges.
      owner: root
      group: exim
      mode:  0750


# , --- letsencrypt --------------------------------------------------------------
- set_fact: hostname_letsencrypt={{ letsencrypt_host_domains | first }}
  when: use_letsencrypt_cert and hostname_letsencrypt is not defined

# ability to use self-signed keys without changing the exim configuration
- file: path=/etc/exim/tls state=directory owner=exim group=mail mode=0750

- name: link to fullchain.pem
  file: src=/etc/letsencrypt/live/{{ hostname_letsencrypt }}/fullchain.pem dest=/etc/exim/tls/fullchain.pem state=link
  when: use_letsencrypt_cert|bool
- name: link to privkey.pem
  file: src=/etc/letsencrypt/live/{{ hostname_letsencrypt }}/privkey.pem dest=/etc/exim/tls/privkey.pem state=link
  when: use_letsencrypt_cert|bool

# force=yes because Exim generates these certificates on its first startup so
# they might not exist so far.
- file: src=/etc/pki/tls/certs/exim.pem dest=/etc/exim/tls/fullchain.pem state=link force=yes
  when: not use_letsencrypt_cert
- file: src=/etc/pki/tls/private/exim.pem dest=/etc/exim/tls/privkey.pem state=link force=yes
  when: not use_letsencrypt_cert

# Exim loads all keys/certificates using its runtime user "exim" - which is not
# allowed to access the certificates directly because letsencrypt allows only
# root access for these (most software loads tls certificates as root).
# https://github.com/letsencrypt/letsencrypt/issues/1473
#  https://github.com/letsencrypt/letsencrypt/pull/1705
#  https://github.com/letsencrypt/letsencrypt/pull/1760
#
# letsencrypt 0.5 should add shell hooks so we could modify filesystem
# ownership/permissions as necessary. Until then we just open up
# /etc/letsencrypt/archive for exim which gives exim access to all certificates.
- name: allow exim access to letsencrypt/archive
  file: path=/etc/letsencrypt/archive state=directory owner=root group=exim mode=0750
  when: use_letsencrypt_cert|bool

- name: allow exim access to letsencrypt/live
  file: path=/etc/letsencrypt/live state=directory owner=root group=exim mode=0750
  when: use_letsencrypt_cert|bool
#` --- letsencrypt --------------------------------------------------------------


- name: validate exim configuration
  command: exim -C /etc/exim/exim.conf -bV
  when: exim_conf.changed or exim_local_conf.changed or exim_role_conf.changed or exim_acls_conf.changed or exim_routers_conf.changed or exim_transports_conf.changed or exim_rewrite_conf.changed or exim_transports_conf.changed

- name: enable exim
  service: name=exim state=started enabled=true

- meta: flush_handlers

