---
# Handlers for common notifications

- name: restart sshd
  service: name=sshd state=reloaded

- name: reload firewalld rules
  command: firewall-cmd --reload

- name: reload systemd units
  command: systemctl daemon-reload

