---

- set_fact: borg_reponame={{ item.borg_reponame }}
- set_fact: borg_client_key={{ item.borg_client_key }}

- set_fact: borg_unix_user="borg-{{ borg_reponame }}"
- set_fact: borg_user_homedir="{{ borg_repo_basedir }}/{{ borg_unix_user }}"

- name: create user {{ borg_unix_user }}
  user:
    name: "{{ borg_unix_user }}"
    state: present
    shell: /bin/bash
    home: "{{ borg_user_homedir }}"
    createhome: yes

- name: create ~borg-{{ borg_reponame }}/.ssh
  file:
    path: "{{ borg_user_homedir }}/.ssh"
    state: directory
    owner: "{{ borg_unix_user }}"
    group: "{{ borg_unix_user }}"
    mode: 0700
    setype: ssh_home_t

- name: set persistent selinux context for ".ssh"
  sefcontext:
    target: "{{ borg_user_homedir }}/.ssh(/.*)?"
    setype: ssh_home_t
    state: present
  when: ansible_selinux.status != 'disabled'

- name: Set authorized key for {{ borg_unix_user }}
  authorized_key:
    user: "{{ borg_unix_user }}"
    state: present
    key: "{{ borg_client_key }}"
    key_options: "command=\"borg serve --restrict-to-path {{ borg_user_homedir }}/{{ borg_reponame }}\",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc"
    exclusive: True

# ansible's "authorized_key" module did not create files with the correct
# SELinux type (ansible 2.9.1 / Dec 2019).
- name: ensure correct SELinux type for .ssh/authorized_keys
  file:
    path: "{{ borg_user_homedir }}/.ssh/authorized_keys"
    setype: ssh_home_t


