---

- name: install borgbackup
  yum:
    name: borgbackup
    state: present

- file: >
    path={{ borg_repo_basedir }}
    state=directory
    owner=root group=root
    mode=0755
    setype=home_root_t

- include: borgrepo.yml
  with_items: "{{ borg_accounts }}"

