---

- name: install borgbackup
  yum:
    name: borgbackup
    state: present

# --- create "borg" user and set up authorized_keys ----------------------------
- user:
    name: borg
    state: present
    shell: /bin/bash
    createhome: yes

- file:
    path: "~borg/.ssh"
    state: directory
    owner: borg
    group: borg
    mode: 0700
    setype: ssh_home_t

- name: set persistent selinux context for "~borg/.ssh"
  sefcontext:
    target: "~borg/.ssh(/.*)?"
    setype: ssh_home_t
    state: present

- name: add borg "master" keys
  authorized_key:
    user: borg
    state: present
    key: "{{ borg_ssh_key }}"
  # when is important to prevent an exception in ansible's "authorized_key" module
  when: borg_ssh_key | length > 0

# ansible's "authorized_key" module did not create files with the correct
# SELinux type (ansible 2.9.1 / Dec 2019).
- name: ensure correct SELinux type for .ssh/authorized_keys
  file:
    path: "~borg/.ssh/authorized_keys"
    setype: ssh_home_t
  # ".ssh/authorized_keys" was only created in the last step if "borg_ssh_key"
  # is set.
  when: borg_ssh_key|bool
# ------------------------------------------------------------------------------


- name: create basedir for borg repos
  file:
    path:   "{{ borg_repo_basedir }}"
    state:  directory
    owner:  root
    group:  root
    mode:   0755

- name: allow access to user directories for "borg" master user by default
  acl:
    path:  "{{ borg_repo_basedir }}"
    entry: default:user:borg:r-x
    state: present

- include: borgrepo.yml
  with_items: "{{ borg_accounts }}"

