---

# Since 2019-12-03 Fedora+EPEL ship etckeeper 1.18.12 with custom patches
# so there is no need for a custom COPR anymore.
#   https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-d4bfeee795
#   https://bodhi.fedoraproject.org/updates/FEDORA-2019-091f76387e
#   https://bugzilla.redhat.com/show_bug.cgi?id=1762693
- name: remove etckeeper copr repo (Fedora)
  file:
    path: /etc/yum.repos.d/fschwarz-etckeeper-fedora.repo
    state: absent

- name: remove etckeeper copr repo (EPEL 8)
  file:
    path: /etc/yum.repos.d/fschwarz-etckeeper-epel-8.repo
    state: absent


- name: install etckeeper
  yum:
    name: etckeeper
    state: present

- name: check if etckeeper is initialized already
  stat: path=/etc/.etckeeper
  register: dot_etckeeper

- command: etckeeper init
  args:
    chdir: /etc
  when: dot_etckeeper.stat.exists == False


- name: check if etckeeper git repo has at least one commit
  stat: path=/etc/.git/refs/heads/master
  register: etckeeper_git

- command: etckeeper commit "initial commit"
  args:
    chdir: /etc
  when: etckeeper_git.stat.exists == False

