---
# This role contains common plays that will run on all nodes.

- include: ssh_server.yml
  tags: sshd

- name: set hostname
  hostname: name={{ hostname|default(ansible_ssh_host|default(inventory_hostname)) }}

- name: set root password
  user: name=root password={{ root_password_hash }}
# can not use the "password_hash()" filter as this would change the password
# change in every ansible run (as root already exists so we can not trigger
# it only once when creating the user)
#  user: name=root password={{ root_password |password_hash('sha512') }}

- name: base packages
  yum: name={{ item }} state=present
  with_items:
    # epel-release is included in CentOS extras which is enabled by default
    - epel-release
    - firewalld
    - cronie

- name: Disable CentOS extras
  copy: src=CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo

# these utilities might include packages from EPEL so it is important that
# "epel-release" was installed before (see "base packages" above)
- name: system utilities
  yum: name={{ item }} state=present
  with_items:
    - wget
    - logrotate
    - sudo
    - ack
    - bash-completion
    - screen
    - mtr
    - htop
    - nano
    - iotop
    - iftop
    - tcpdump

- include: etckeeper.yml
  tags: etckeeper





- include: systemd-networkd.yml
  tags: systemd-networkd

- include: systemd-resolved.yml
  tags: systemd-resolved


# This removes a couple of services to save RAM (quite a bit, about 50 MB!)
# also less running services means reduced attack surface.
- name: remove packages
  yum: name={{ item }} state=absent
  with_items:
    - tuned             # only necessary for power saving modes for SATA/ethernet
    # items which were only installed for NetworkManager
    # avahi, polkit and wpa_supplicant are daemons so uninstalled them will
    # also reduce memory usage
    - jansson
    - avahi-libs        # no need for service autodiscovery
    - wpa_supplicant    # our servers don't have WLAN
    - polkit            # also removes NetworkManager
    - mozjs17

- include: ntp.yml
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: redirect mails for root to server admin email
  lineinfile:
    dest: /etc/aliases
    # need single-quotes here to avoid yaml syntax error
    # https://github.com/ansible/ansible/issues/1341
    regexp: '^\s*root:'
    line: "root:		{{ admin_emails | join(', ') }}"
    state: present

- meta: flush_handlers

