---
- name: install ntp
  yum: name=ntp state=present

- name: Configure ntp file
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=true

