---

- name: SSH Keys
  authorized_key: >
    user=root
    exclusive=True
    key="{{ (ssh_root_keys + ssh_root_keys_for_group | default([])) | join('\n') }}"
  tags: ssh_keys

- group: name=sftponly

- name: sftp space
  file: >
    state=directory
    path=/srv/sftp
    owner=root group=root
    mode=0551

- name: copy sshd_config (CentOS 7)
  copy: src="sshd_config.c7" dest=/etc/ssh/sshd_config
  notify: restart sshd
  when: is_centos7

- name: copy sshd_config (CentOS 8+Fedora)
  copy: src="sshd_config.c8_fed" dest=/etc/ssh/sshd_config
  notify: restart sshd
  when: is_centos8 or is_fedora

- name: copy ssh/config
  copy: src="ssh_config" dest=/etc/ssh/ssh_config

- name: copy ssh/known_hosts
  copy: src="ssh_known_hosts" dest=/etc/ssh/known_hosts

- name: Start sshd
  service: name=sshd state=started enabled=true

- firewalld: port=22/tcp immediate=true permanent=true state=enabled

- include: sshguard.yml
  tags: sshguard
  when: sshguard == True

- meta: flush_handlers

