---

- name: SSH Keys
  authorized_key: user=root key="{{ item }}"
  with_items:
    - "{{ ssh_root_keys }}"
    - "{{ ssh_root_keys_for_group | default([]) }}"
  tags: ssh_keys
  no_log: True

- name: Remove obsolete SSH Keys
  authorized_key: state=absent user=root key="{{ item }}"
  with_items: ssh_obsolete_root_keys
  when: "{{ ssh_obsolete_root_keys | default([]) }}"
  tags:
    - ssh_keys
  no_log: True

- group: name=sftponly

- name: sftp space
  file: >
    state=directory
    path=/srv/sftp
    owner=root group=root
    mode=0551

- name: Configure sshd file
  copy: src="sshd_config.c{{ ansible_distribution_major_version }}" dest=/etc/ssh/sshd_config
  notify: restart sshd
  when: ansible_distribution == "CentOS"

- name: Start sshd
  service: name=sshd state=started enabled=true

- firewalld: port=22/tcp permanent=true state=enabled

- meta: flush_handlers

