---

- name: SSH Keys
  authorized_key: >
    user=root
    exclusive=True
    key="{{ (ssh_root_keys + ssh_root_keys_for_group | default([])) | join('\n') }}"
  tags: ssh_keys

- group: name=sftponly

- name: sftp space
  file: >
    state=directory
    path=/srv/sftp
    owner=root group=root
    mode=0551

- name: Configure sshd file
  copy: src="sshd_config.c{{ ansible_distribution_major_version }}" dest=/etc/ssh/sshd_config
  notify: restart sshd
  when: ansible_distribution == "CentOS"

- name: Start sshd
  service: name=sshd state=started enabled=true

- firewalld: port=22/tcp permanent=true state=enabled

- meta: flush_handlers

