---

# configure networking using systemd-networkd to the maximum extend
# - utilities are pretty slim (saves quite a bit of RAM)
# - utilities are *really* well integrated/handling a lot of edge cases
# - a lot of functionality (e.g. trivial DNS caching, DNSSEC for systemd 229+)
# - configuration is easily readable
#
# The only downside is that Red Hat disables several features in RHEL:
# - timesyncd (which knows about wait-online, just has an NTP client - less RAM, no accidental reflection attacks possible)
# - user sessions in logind (no user-specific service management)
- name: install systemd-networkd
  yum: name={{ item }} state=present
  with_items:
    - systemd-networkd

- name: create /etc/systemd/network
  file: path=/etc/systemd/network state=directory

- name: configure networkd
  copy: src=host_files/{{ inventory_hostname }}/10-eth0.network dest=/etc/systemd/network/10-eth0.network

- name: stop NetworkManager
  service: name=NetworkManager    state=stopped enabled=false

- name: remove NetworkManager
  yum: name={{ item }} state=absent
  with_items:
    - NetworkManager

- name: enable systemd-networkd
  service: name=systemd-networkd    state=started enabled=true

- name: enable systemd-networkd-wait-online
  service: name=systemd-networkd-wait-online    state=started enabled=true

- name: disable legacy network scripts
  # we must not stop the legacy "network" service as this would immediately
  # stop all network connections. Instead just leave it running and just disable
  # the old service - "systemd-networkd" will take over after the next reboot.
  # (btw not using the old init script saves about 5-10 MB RAM)
  service: name=network    enabled=false

- name: ensure that firewalld applies to eth0
  shell: /usr/bin/firewall-cmd --permanent --zone=public --add-interface=eth0

