---

- name: install yum-cron
  yum: name=yum-cron state=present

- name: copy yum-cron.conf
  copy: src=yum-cron.conf dest=/etc/yum/yum-cron.conf mode=0644

- name: copy yum-cron.conf
  copy: src=yum-cron.conf dest=/etc/yum/yum-cron.conf mode=0644

- name: copy yum-daily cronjob
  copy: src=0yum-daily.cron dest=/etc/cron.daily/0yum-daily.cron mode=0755

- name: copy yum-hourly cronjob
  copy: src=0yum-hourly.cron dest=/etc/cron.hourly/0yum-hourly.cron mode=0755

- name: enable yum-cron.service
  service: name=yum-cron state=started enabled=true

