---

- name: install yum-cron
  yum: name=yum-cron state=present

- name: generate yum-cron.conf
  template:
    src: yum-cron.conf.j2
    dest: /etc/yum/yum-cron.conf
    mode: 0644

- name: enable yum-cron.service
  service: name=yum-cron state=started enabled=true

