---

- set_fact: hostname_letsencrypt={{ letsencrypt_host_domains[0] }}
  when: use_letsencrypt_cert

- name: install letsencrypt package
  yum: name={{ item }} state=present
  with_items:
    - letsencrypt

# needed to for acme challenges
- name: open port 80 in the firewall
  firewalld: port=80/tcp permanent=true immediate=true state=enabled
  when: use_letsencrypt_cert

# /etc/letsencrypt is owned by the letsencrypt rpm but only created when the
# program is executed for the first time. I'd like to put the client.ini in
# /etc/letsencrypt (see below) so we need to create the directory first.
- name: create /etc/letsencrypt
  file: path=/etc/letsencrypt state=directory owner=root group=root mode=0755

# jinja2 template so we can have a dynamic admin email address
- name: generate client.ini
  template: src=letsencrypt.ini.j2 dest={{ letsencrypt_ini_path }} owner=root group=root mode=0640

- name: check if host already has a letsencrypt cert
  stat: path=/etc/letsencrypt/live/{{ hostname_letsencrypt }}/fullchain.pem
  when: use_letsencrypt_cert
  register: letsencrypt_hostcert

- name: generate letsencrypt host cert
  shell: letsencrypt certonly --config {{ letsencrypt_ini_path }} -d {{ letsencrypt_host_domains | join(' -d ') }}
  when: use_letsencrypt_cert and (letsencrypt_hostcert.stat.exists == False)




